"""Mock retrieval data for testing without Sanjana's real output."""

MOCK_RETRIEVAL_RESPONSE_DRAINAGE = {
    "query": "my washing machine won't drain",
    "reranked_top_5": [
        {
            "rank": 1,
            "chunk_id": "whirlpool_washer_drain_1",
            "text": "If water won't drain from your washer, first check the drain pump filter for clogs. Drain filter clogs are one of the most common causes of drainage issues. The filter is usually located at the bottom front of the machine.",
            "source_url": "https://www.whirlpool.com/en-us/support/washers/drainage",
            "heading_path": "Troubleshooting > Drainage Issues",
            "page_type": "support_page",
            "effective_date": "2024-07-01",
            "pre_rerank_score": 0.87,
            "post_rerank_score": 0.95,
        },
        {
            "rank": 2,
            "chunk_id": "whirlpool_washer_hoses_1",
            "text": "Check the inlet hoses for kinks or damage that might restrict water flow. Kinked hoses can prevent proper drainage and water fill. Straighten any bent hoses and replace if damaged.",
            "source_url": "https://www.whirlpool.com/en-us/support/washers/hoses",
            "heading_path": "Maintenance > Inlet Hoses",
            "page_type": "support_page",
            "effective_date": "2024-06-15",
            "pre_rerank_score": 0.82,
            "post_rerank_score": 0.88,
        },
        {
            "rank": 3,
            "chunk_id": "ge_washer_drain_1",
            "text": "For GE washers, drainage problems often stem from a blocked drain hose. Remove the drain hose from the back of the machine and check for blockages. You can use a plumbing snake to clear any debris.",
            "source_url": "https://www.ge.com/appliances/support/washers/drainage",
            "heading_path": "Troubleshooting > Drain Hose",
            "page_type": "support_page",
            "effective_date": "2024-07-05",
            "pre_rerank_score": 0.78,
            "post_rerank_score": 0.84,
        },
        {
            "rank": 4,
            "chunk_id": "whirlpool_error_codes_1",
            "text": "Error code F21 indicates a drainage failure. This usually means the drain pump is not working or the filter is blocked. Restart the cycle after clearing the filter.",
            "source_url": "https://www.whirlpool.com/en-us/support/washers/error-codes",
            "heading_path": "Error Codes > F21",
            "page_type": "support_page",
            "effective_date": "2024-07-01",
            "pre_rerank_score": 0.75,
            "post_rerank_score": 0.81,
        },
        {
            "rank": 5,
            "chunk_id": "ge_washer_pump_1",
            "text": "If your GE washer still won't drain after checking the filter and hose, the drain pump may be faulty and require replacement. Contact customer service for repair options.",
            "source_url": "https://www.ge.com/appliances/support/washers/drain-pump",
            "heading_path": "Troubleshooting > Drain Pump",
            "page_type": "support_page",
            "effective_date": "2024-06-20",
            "pre_rerank_score": 0.71,
            "post_rerank_score": 0.77,
        },
    ],
}

MOCK_RETRIEVAL_RESPONSE_REPAIR = {
    "query": "how do I repair my dishwasher door latch",
    "reranked_top_5": [
        {
            "rank": 1,
            "chunk_id": "ge_dishwasher_latch_1",
            "text": "If your dishwasher door won't latch, first check if dishes are blocking the door. Remove any items that may be preventing a full close. The door should close firmly with a clicking sound.",
            "source_url": "https://www.ge.com/appliances/support/dishwashers/door-latch",
            "heading_path": "Troubleshooting > Door Won't Close",
            "page_type": "support_page",
            "effective_date": "2024-07-01",
            "pre_rerank_score": 0.89,
            "post_rerank_score": 0.96,
        },
        {
            "rank": 2,
            "chunk_id": "ge_dishwasher_alignment_1",
            "text": "Check if the door is properly aligned with the frame. Misalignment can prevent the latch from catching. Adjust the hinges if needed using the screws on the inside of the door.",
            "source_url": "https://www.ge.com/appliances/support/dishwashers/door-alignment",
            "heading_path": "Maintenance > Door Alignment",
            "page_type": "support_page",
            "effective_date": "2024-06-25",
            "pre_rerank_score": 0.84,
            "post_rerank_score": 0.91,
        },
        {
            "rank": 3,
            "chunk_id": "whirlpool_dishwasher_latch_1",
            "text": "Whirlpool dishwasher latches may wear out over time. If the door won't stay latched even when properly aligned, the latch assembly may need replacement. This is a common maintenance item.",
            "source_url": "https://www.whirlpool.com/en-us/support/dishwashers/latches",
            "heading_path": "Maintenance > Latch Assembly",
            "page_type": "support_page",
            "effective_date": "2024-07-10",
            "pre_rerank_score": 0.79,
            "post_rerank_score": 0.86,
        },
        {
            "rank": 4,
            "chunk_id": "ge_dishwasher_springs_1",
            "text": "Door springs help close the dishwasher door. If springs are broken or loose, the door may not close properly. Check and replace springs if necessary.",
            "source_url": "https://www.ge.com/appliances/support/dishwashers/springs",
            "heading_path": "Maintenance > Door Springs",
            "page_type": "support_page",
            "effective_date": "2024-06-18",
            "pre_rerank_score": 0.76,
            "post_rerank_score": 0.82,
        },
        {
            "rank": 5,
            "chunk_id": "whirlpool_dishwasher_service_1",
            "text": "For complex dishwasher repairs, we recommend contacting an authorized Whirlpool service center. They have the right parts and expertise for safe repairs.",
            "source_url": "https://www.whirlpool.com/en-us/support/dishwashers/service",
            "heading_path": "Support > Service Centers",
            "page_type": "support_page",
            "effective_date": "2024-07-05",
            "pre_rerank_score": 0.72,
            "post_rerank_score": 0.78,
        },
    ],
}

MOCK_RETRIEVAL_RESPONSE_LOW_CONFIDENCE = {
    "query": "what is the optimal temperature for washing delicate fabrics",
    "reranked_top_5": [
        {
            "rank": 1,
            "chunk_id": "misc_1",
            "text": "General washing machine user guide mentions temperature settings.",
            "source_url": "https://www.example.com/guides",
            "heading_path": "Guides > General",
            "page_type": "faq",
            "effective_date": "2024-01-01",
            "pre_rerank_score": 0.32,
            "post_rerank_score": 0.38,
        },
        {
            "rank": 2,
            "chunk_id": "misc_2",
            "text": "Some information about washers.",
            "source_url": "https://www.example.com/info",
            "heading_path": "Info > Washers",
            "page_type": "faq",
            "effective_date": "2024-01-01",
            "pre_rerank_score": 0.28,
            "post_rerank_score": 0.31,
        },
        {
            "rank": 3,
            "chunk_id": "misc_3",
            "text": "Product information page.",
            "source_url": "https://www.example.com/products",
            "heading_path": "Products > Washers",
            "page_type": "product",
            "effective_date": "2024-01-01",
            "pre_rerank_score": 0.25,
            "post_rerank_score": 0.27,
        },
        {
            "rank": 4,
            "chunk_id": "misc_4",
            "text": "Another page with limited info.",
            "source_url": "https://www.example.com/other",
            "heading_path": "Other",
            "page_type": "faq",
            "effective_date": "2024-01-01",
            "pre_rerank_score": 0.22,
            "post_rerank_score": 0.24,
        },
        {
            "rank": 5,
            "chunk_id": "misc_5",
            "text": "Related content.",
            "source_url": "https://www.example.com/related",
            "heading_path": "Related",
            "page_type": "faq",
            "effective_date": "2024-01-01",
            "pre_rerank_score": 0.20,
            "post_rerank_score": 0.21,
        },
    ],
}

def get_mock_response(query_type: str = "drainage"):
    """Get mock retrieval response for testing."""
    mock_responses = {
        "drainage": MOCK_RETRIEVAL_RESPONSE_DRAINAGE,
        "repair": MOCK_RETRIEVAL_RESPONSE_REPAIR,
        "low_confidence": MOCK_RETRIEVAL_RESPONSE_LOW_CONFIDENCE,
    }
    return mock_responses.get(query_type, MOCK_RETRIEVAL_RESPONSE_DRAINAGE)
